### ISSUE TITLE
SSL error connecting to Digital Ocean managed MySQL

### ISSUE THREAD

**Issue by blackpond** [brianmario/mysql2#1072]
Hi,

I can connect no problem from my local machine, but my server is unable to connect to Digital Ocean's new managed MySQL service.  Documentation is pretty light so I was hoping someone here could give me some insight.

Rails 6, Ruby 2.6.3, Ubuntu 18.04.3, MySQL 8

Here is the error:

```
      [deploy:migrate] Run `rake db:migrate`
00:30 deploy:migrating
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake db:migrate
      01 rake aborted!
      01 Mysql2::Error::ConnectionError: SSL connection error: unknown error number
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `connect'
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `initialize'
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:879:in `new_connection'
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:923:in `checkout_new_connecti…
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:902:in `try_to_checkout_new_c…
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:863:in `acquire_connection'
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:587:in `checkout'
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:431:in `connection'
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:1111:in `retrieve_connection'
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_handling.rb:231:in `retrieve_connection'
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_handling.rb:199:in `connection'
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:85:in `block (3 levels) in <main>'
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:83:in `each'
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:83:in `block (2 levels) in <main>'
      01 /home/deploy/my_app/shared/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
      01 /home/deploy/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
      01 /home/deploy/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'
      01 Tasks: TOP => db:migrate
      01 (See full trace by running task with --trace)
#<Thread:0x00007f8d2c8e3490@/Users/Admin/.rvm/gems/ruby-2.6.3/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	13: from /Users/Admin/.rvm/gems/ruby-2.6.3/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
	12: from /Users/Admin/.rvm/gems/ruby-2.6.3/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:31:in `run'
	11: from /Users/Admin/.rvm/gems/ruby-2.6.3/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
	10: from /Users/Admin/.rvm/gems/ruby-2.6.3/gems/capistrano-rails-1.4.0/lib/capistrano/tasks/migrations.rake:23:in `block (3 levels) in <top (required)>'
	 9: from /Users/Admin/.rvm/gems/ruby-2.6.3/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:92:in `within'
	 8: from /Users/Admin/.rvm/gems/ruby-2.6.3/gems/capistrano-rails-1.4.0/lib/capistrano/tasks/migrations.rake:24:in `block (4 levels) in <top (required)>'
	 7: from /Users/Admin/.rvm/gems/ruby-2.6.3/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:100:in `with'
	 6: from /Users/Admin/.rvm/gems/ruby-2.6.3/gems/capistrano-rails-1.4.0/lib/capistrano/tasks/migrations.rake:25:in `block (5 levels) in <top (required)>'
	 5: from /Users/Admin/.rvm/gems/ruby-2.6.3/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:80:in `execute'
	 4: from /Users/Admin/.rvm/gems/ruby-2.6.3/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
	 3: from /Users/Admin/.rvm/gems/ruby-2.6.3/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:148:in `tap'
	 2: from /Users/Admin/.rvm/gems/ruby-2.6.3/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
	 1: from /Users/Admin/.rvm/gems/ruby-2.6.3/gems/sshkit-1.20.0/lib/sshkit/backends/netssh.rb:170:in `execute_command'
/Users/Admin/.rvm/gems/ruby-2.6.3/gems/sshkit-1.20.0/lib/sshkit/command.rb:97:in `exit_status=': rake exit status: 1 (SSHKit::Command::Failed)
rake stdout: Nothing written
rake stderr: rake aborted!
```

Here are the credentials I was given from DO:

```
username = doadmin
password = mypassword
host = myapp-mysql-do-user-123456-0.db.ondigitalocean.com
port = 12345
database = defaultdb
sslmode = REQUIRED
```

And here is my database.yml (development works, , but production doesn't)

```
development:
  adapter: mysql2
  database: defaultdb
  username: doadmin
  password: mypassword
  host: myapp-mysql-do-user-123456-0.db.ondigitalocean.com
  ssl_mode: REQUIRED
  port: 12345

production:
  adapter: mysql2
  database: defaultdb
  username: doadmin
  password: mypassword
  host: myapp-mysql-do-user-123456-0.db.ondigitalocean.com
  ssl_mode: REQUIRED
  port: 12345
```

**Comment by fatfrog** [comment]
Sorry, please close - I didn't have libmysqlclient-dev installed.  Interestingly enough, the way I discovered this is that 0.5.0 of the gem wouldn't install without it, unlike 0.5.2

**Comment by vitobotta** [comment]
Hi @fatfrog ! I didn't notice that there was already an issue about this... Can you clarify how you fixed? I am having exactly the same issue with the DO managed MysQL. In my Docker image I install libmysql-client-dev for MySQL 8.0 which is what I have with DO, but when Rails starts I get the same `unknown error number`. The only difference from your configuration is that I am using the connection string provided by DO instead of the host/username/etc settings separately. Thanks in advance!

**Comment by fatfrog** [comment]
Do you have both mysql-client and  libmysqlclient-dev installed?  I was good to go once they where both installed.  Have you tried connecting via MySQL GUI like MysQL Workbench or Sequel Pro?

**Comment by vitobotta** [comment]
Hi @fatfrog yes, I have  both installed and can connect fine with the CLI mysql client but it doesn't work with the Sequel Pro GUI client for Mac either... I'm lost.... I thought this would take a few minutes :(

**Comment by vitobotta** [comment]
I get exactly the same error with Sequel Pro btw, same message

**Comment by vitobotta** [comment]
Aha, I had to install libmysqlclient20 because otherwise MySQL2 gem would complain about that, and that library is for MySQL 5.7. How do I get this gem to work with 8.0? I'm using the latest version 0.5.2.

**Comment by vitobotta** [comment]
The message I have without that package installed is this:

```
libmysqlclient.so.20: cannot open shared object file: No such file or directory - /home/rails/bundle/gems/mysql2-0.5.2/lib/mysql2/mysql2.so (LoadError)
```

**Comment by fatfrog** [comment]
In Sequel Pro, you need to do the following:

For clients that support the "mysql_native_password" authentication, the above encryption type won't work. The below command can be used to change the authentication for the user after creation.

ALTER USER myuser IDENTIFIED WITH mysql_native_password BY 'mypassword';

**Comment by vitobotta** [comment]
@fatfrog   Will try that but my priority is Rails.

Hey you are not specifying the CA certificate in your configuration are you? The one that you download from DO control panel? I just managed to connect without specifying the certificate and using the master branch instead of the latest version of the gem. Is it using SSL this way though? I want to make sure traffic between the database and the servers is encrypted. This issue should be reopened imo @sodabrew

**Comment by fatfrog** [comment]
This is what DO sent me regarding the certificate:

Hello,

Glad to hear that everything is working as of now. Generally, the CA certificate isn't needed although it can be used by the client to establish trust with the remote server. Since it's just used for the SSL handshake, it won't be able to be used for authentication. If you have any other questions or concerns, please don't hesitate to let us know. 

Swimmingly,
Garrett Jansen
Developer Support Engineer
DigitalOcean

**Comment by vitobotta** [comment]
Wonderful, thanks a lot @fatfrog !

**Comment by vitobotta** [comment]
@fatfrog Hi! I am having another weird problem now where if I run `rails db:migrate` or `rails db:schema:dump` in my development environment (which is running in Kubernetes and uses DO's managed MySQL), the generated schema.rb is invalid. If I run those tasks in a test container connected to a local instance of MySQL 8.0.17 (the same as DO), but with RAILS_ENV set to `development`, the schema.rb is perfectly valid. See https://github.com/rails/rails/issues/37706 for examples of the difference between the schema.rb's generated in my development and test environments - dev connected to DO, test connected to local MySQL.

Would you be so kind as to run a `db:schema:dump` while connected to DO's MySQL, and see what kind of schema.rb it produces? In particular, if the `options` setting for the `create_table` blocks is set to something like `"ENGINE=InnoDB DEFAULT CHARSET=utf8"` then it's valid syntax. If instead, with it sets `options` to a full `CREATE TABLE` SQL statement like it happens for me, then it's invalid syntax (e.g. `db:schema:load` will fail).

I would appreciate if you could try this because I don't know what else to try and so far everything seems to point to DO. Thanks!

**Comment by vitobotta** [comment]
Just to clarify in case it's confusing: my dev environment, like staging and prod, runs in DO's managed Kubernetes and thus it uses DO's managed MySQL.
