### ISSUE TITLE
Support for openGIS

### ISSUE THREAD

**Issue by guizmaii** [brianmario/mysql2#650]
Hi,

Do you plan to support the spatial data types (https://dev.mysql.com/doc/refman/5.0/en/spatial-datatypes.html) and the Spatial analysis functions (https://dev.mysql.com/doc/refman/5.0/en/spatial-analysis-functions.html) ?

**Comment by sodabrew** [comment]
You can already use columns and functions of these types, but you'll get the results back as strings. You'd then need to convert the strings into your own representations.

The big feature of mysql2 is that it will do the data type conversions in C code rather than in Ruby code, for a significant performance boost. If there are Ruby objects that can represent these types, then it would make sense to provide direct conversions from the MySQL data types into the Ruby data types.

**Comment by sodabrew** [comment]
See also #619, the previous poster seemed to be looking for ActiveRecord support for spatial types.

**Comment by sodabrew** [comment]
I suggest https://github.com/rgeo/rgeo and https://github.com/rgeo/rgeo-activerecord. Good luck!
