### ISSUE TITLE
Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by detrix42** [brianmario/mysql2#758]
I have posted the following question on Stackoverflow. Would you please review it and see if there is something that can be done?

[http://stackoverflow.com/questions/37639935/ruby-rails-access-denied-for-user-rootlocalhost-using-password-yes]

**Comment by sodabrew** [comment]
Looks like a fine question to get help on troubleshooting your work. Stack Overflow is a great place for it. Good luck!

The fellow who asks why your error has to do with the root user but your posted config states `username: cmsapp` is asking a very important question - either you are asking for help by posting inconsistent configs which is going to make it hard for others to help you (of course you should zero out passwords and host names and such, but don't forget that this might change the error! That's part of troubleshooting!), or you actually have inconsistent configs causing the confusion (e.g. If your configs are in two places but only one is being used, the other is a red herring).

**Comment by detrix42** [comment]
you missed the point completely.  Regardless of which app I refer to, the point is that your mysql connector does not parse the following line correctly:
password: <%= ENV['MYSQLROOT_PASSWORD'] %>

It does not matter if I use MYSQLROOT_PASSWORD or MYCMSAPP_PASSWORD this line DOES NOT retreive the environment variable.  

I have switched back to the orginal mysql gem and everything works great.  So until your mysql adapter can use environment variables, I can't use it.

**Comment by sodabrew** [comment]
The translation of that environment variable does not happen inside the mysql gem, nor in the mysql2 gem. It happens when Rails loads the config file. I don't know why it's not working, and absolutely did not miss the point in trying to point you in the right direction.

**Comment by brianmario** [comment]
@detrix42 Rails itself is responsible for processing the `database.yml` file using `ERB` first. Only then does it parse it with the `YAML` library.

[Here](https://github.com/rails/rails/blob/4-2-stable/railties/lib/rails/application/configuration.rb#L104) is the line of code In Rails 4.2.x responsible for doing that. From there, it takes the returned hash and passed _that_ value to this gem. But by that point, any of these `ERB` statements like `<%= ENV['MYSQLROOT_PASSWORD'] %>` have been processed and turned into values.

The error message you provided leaves me to believe a password value _is_ being passed, it's just not correct. But to @sodabrew's point, the username in the error message is `root` but the username in your `database.yml` (at least according to the one you specified in the stackoverflow article) is `cmsapp`. That means Rails is either using a different `database.yml`, didn't find one at all, or something else is misconfigured in your environment.

As a last troubleshooting measure - could you try seeing what the value of `ActiveRecord::Base.configurations["development"]` is in your rails console? That's the hash of info that Rails ends up passing to the mysql2 gem. So if something in there doesn't look right, the issue is somewhere else in your environment, not this gem.

Let us know if that helps in tracking down the issue.

**Comment by detrix42** [comment]
@sodabrew I do apologize. I am still not sure why. I have decided to figure it out later.  I will just use the password directly in database.yml for now.  I have edited my previous comment to be more friendly.

**Comment by ruimigueltrigo** [comment]
I managed to fix this issue. Turns out I was using ' (single quotes) instead of " (double quotes). For anyone who this might be useful:

On YAML file, the following produces this issue's error:
<%= ENV['SECRET_KEY_BASE'] %>

fix:
<%= ENV["SECRET_KEY_BASE"] %>
