### ISSUE TITLE
Mysql2::Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead:

### ISSUE THREAD

**Issue by heimatau** [brianmario/mysql2#784]
I'm using Rails 4.0.0, mySQL 5.7.14, activerecord (5.0.0.1, 4.0.0) and gem mysql2 0.3.18. And I keep running in circles. If I need to share more info, just ask and I'll update it here.

First issue that keeps coming up is:

> Mysql2::Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead:

And my second issue, i currently can't reproduce it but it boils down to trying [this](http://stackoverflow.com/a/34555109/3685632) which ultimately causes the error: Mysql2.....(NameError). And if I try a 'super' snippet, that is similar to the SO answer (I miss placed it but code is below for the config/initializers/abstract_mysql2_adapter.rb file), then I get a super mismatch.

`class ActiveRecord::ConnectionAdapters::Mysql2Adapter
 def modify_types(types)
   super
   types[:primary_key] = "int(11) auto_increment PRIMARY KEY"
   types
 end
end`

I'd like to use Rails 4 since that's what the lesson is in. How do I fix this and/or how would I find the answer?

**Comment by kamipo** [comment]
Seems like that adding `require 'active_record/connection_adapters/mysql2_adapter'` solves NameError.

**Comment by heimatau** [comment]
Where would I add that?

**Comment by kamipo** [comment]
```ruby
# config/initializers/abstract_mysql2_adapter.rb

require 'active_record/connection_adapters/mysql2_adapter'

class ActiveRecord::ConnectionAdapters::Mysql2Adapter
  NATIVE_DATABASE_TYPES[:primary_key] = "int(11) auto_increment PRIMARY KEY"
end
```

**Comment by heimatau** [comment]
Thank you! That worked nicely. So far, I haven't seen any issues.

**Comment by rishabh-tripathi** [comment]
For activerecord-3.2.11, this worked for me,

require 'active_record/connection_adapters/abstract_mysql_adapter'
class ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter
NATIVE_DATABASE_TYPES[:primary_key] = "int(11) auto_increment PRIMARY KEY"
end

**Comment by Ramit-Pahwa** [comment]
i am new to this trying to set up in mac os siera not able to navigate where file nees to be added

**Comment by saraomb** [comment]
I use  Ubnutu and cann't find the path "active_record/connection_adapters/mysql2_adapter"
Does anyone know where its located in Ubnutu?

**Comment by sodabrew** [comment]
Please don't add new questions to old (and closed!) issues.

Stack Overflow is a great resource for help on basic Rails setup questions. I hope you're able to find solutions there! https://stackoverflow.com/questions/tagged/ruby-on-rails

**Comment by coldnebo** [comment]
This error still lingers in Rails 3 projects, so I'm documenting the complete fix (for @Ramit-Pahwa) and the background so you can determine whether this fix is appropriate for your situation.

As @kamipo suggested above (and in https://stackoverflow.com/a/40758542), the solution is to create an initializer in your Rails app directory at `./config/initializers/abstract_mysql2_adapter.rb`:

```ruby
require 'active_record/connection_adapters/mysql2_adapter'

class ActiveRecord::ConnectionAdapters::Mysql2Adapter
  NATIVE_DATABASE_TYPES[:primary_key] = "int(11) auto_increment PRIMARY KEY"
end
```

## Background

This error exists because of code drift between the mysql adapter in Rails and MySQL features over time.  

Rails 3 creates primary keys with `int(11) DEFAULT NULL auto_increment PRIMARY KEY` which used to work in MySQL < 5.7.3.  However with the release of MySQL 5.7.3 [this behavior was prohibited](https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-3.html):

> Columns in a PRIMARY KEY must be NOT NULL, but if declared explicitly as NULL produced no error. Now an error occurs. For example, a statement such as CREATE TABLE t (i INT NULL PRIMARY KEY) is rejected. The same occurs for similar ALTER TABLE statements. (Bug #13995622, Bug #66987, Bug #15967545, Bug #16545198)
 
Consequently, MySQL's change caused [an issue](https://github.com/rails/rails/issues/13203) in Rails and [was later fixed by this commit](https://github.com/rails/rails/commit/b6655885ef13cf8d1705dc9b5232846f0207febd) in Rails 4.1.0.beta1 and later.  Unfortunately, the fix was never backported to Rails 3, likely because it fell off support before the change was made.  The initializer fix above is essentially a backport of this fix to Rails 3 apps that might be using upgraded MySQL databases >= 5.7.3.

**Comment by ramror3** [comment]
@kamipo.  Thanks for giving.

**Comment by liujiang04** [comment]
what about  windows？

**Comment by EdOverride** [comment]
for rails version `3.2.8`, u need to do this:

```ruby
require 'active_record/connection_adapters/abstract_mysql_adapter'

class ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter
  NATIVE_DATABASE_TYPES[:primary_key] = "int(11) auto_increment PRIMARY KEY"
end
```

That worked for me.
