### ISSUE TITLE
How do we re-try transactions with mysql2?

### ISSUE THREAD

**Issue by merrr224** [brianmario/mysql2#823]
How do we re-try transactions with mysql2? Do you have any method for it?
I would appreciate it if you could let us know.
Best regards.

**Comment by sodabrew** [comment]
One answer is that "it depends" - if you're using a framework like ActiveRecord, or if you're directly writing code with the Mysql2::Client object - there will be some differences in how the SQL is wrapped with code.

But the common thread is that you must do the re-try yourself in your application code, because only your application code will know if there are other side-effects that need to be coordinated.

The basic idea is to wrap the SQL calls in a `begin ... rescue` block:

``` ruby
@client = Mysql2::Client.new(...connection parameters...)
begin
  @client.query("START TRANSACTION")
  @client.query("SELECT some data....")
  @client.query("UPDATE table one...")
  @client.query("UPDATE table two...)
  @client.query("COMMIT")
rescue
  ... some code to handle the exception, and maybe to retry the SQL queries, etc...
end
```

**Comment by merrr224** [comment]
I understood very well.
Thanks.

**Comment by carsonreinke** [comment]
If you are using ActiveRecord and need something quick, try the [transaction_retry](https://github.com/qertoip/transaction_retry) gem.
