### ISSUE TITLE
How I can use prepared statements for "WHERE IN (?)"?

### ISSUE THREAD

**Issue by tit** [brianmario/mysql2#856]
I wanna prepare and execute next query:
```ruby
statement = client.prepare 'SELECT * FROM `table_name` WHERE `id` IN (?);'
statement.execute [1, 2, 3]
# or
statement.execute '1, 2, 3'
```
Both options do not work.
Is there any way to make the preparation and execution of the query, where is the array transferred to the variable?

**Comment by dylanahsmith** [comment]
`statement = client.prepare 'SELECT * FROM `table_name` WHERE `id` IN (?);'`

prepares a statement that takes a single parameter, where parameter types are limited to the types supported by the MYSQL API as documented in https://dev.mysql.com/doc/refman/5.7/en/c-api-prepared-statement-type-codes.html.  All those types are scalar types, so the mysql client C API doesn't support passing an array as a prepared statement parameter.

So for that statement you are able to do `statement.execute(1)`, but you can't pass in an array of integers.  Perhaps you are expecting this to work since it works in Active Record, but the string substitution is done outside of the mysql2 gem before the query is sent to mysql.

Perhaps the mysql2 gem should make this programming error more obvious, since it has a [switch statement and some `if else` statements](https://github.com/brianmario/mysql2/blob/0.4.6/ext/mysql2/statement.c#L298-L404) to handle certain ruby types, but doesn't do anything for any unhandled type.  It looks like is ends up using a decimal value of 0.0, because the memory for the `bind_buffers` is zero allocated and MYSQL_TYPE_DECIMAL has a value of 0.  This can be seen demonstrated with

```
irb> client.prepare('SELECT ?').execute([1, 2, 3]).to_a
=> [{"?"=>#<BigDecimal:7f866b87fa98,'0.0',9(18)>}]
```

I would prefer if the mysql2 gem raised in this case to make this error obvious to the programmer.

When you pass a string in to the statement as you did with `statement.execute '1, 2, 3'`, mysql will coerce that to an integer for the comparison as `atoi` converts a string to an integer in C.  That is a lossy conversion, so it will actually convert the string to `1`.  This can be demonstrated with

```
mysql> SELECT 1 = '1, 2, 3';
+---------------+
| 1 = '1, 2, 3' |
+---------------+
|             1 |
+---------------+
```

I don't like this lossy conversion that mysql is doing, but it doesn't have to do with the mysql2 gem.

**Comment by tit** [comment]
Thanx! I understand it.
