### ISSUE TITLE
i need help to find tables in my database

### ISSUE THREAD

**Issue by shashank4412** [brianmario/mysql2#927]
I have searched a lot about how to display the tables in the database, but nothing is clear to me,
basically i want to create new table and also display all of them in the database but i don't know how.
I'm creating a GUI application with MySQL database. (i am using shoes GUI toolkit in ruby)
need your help.

**Comment by sodabrew** [comment]
I think you'll be better served for your project on Stack Overflow, which has a broad and engaged community to help with database and programming questions.

This issue tracker is mostly just me, and what you're asking isn't specific to this gem, it's a very general question about MySQL. I wish you lots of luck in your project!

`SHOW TABLES` is the query you want to run.

There actually is a C API `mysql_list_tables()` but this gem does not implement it, because the query above is more commonly used.

**Comment by simi** [comment]
*@sodabrew I'm reading issues as well. Don't worry, you're not alone here.*
