### ISSUE TITLE
Mysql2::Error: Field 'created_at' doesn't have a default value

### ISSUE THREAD

**Issue by solaiman** [brianmario/mysql2#945]
I'm using mysql2 (0.4.10) and rails(5.1.4). Whenever I going to create a record getting error
Mysql2::Error: Field 'created_at' doesn't have a default value.

please help.

**Comment by sodabrew** [comment]
I'll be glad to help a bit, but this isn't a question specific to the mysql2 gem. It's general to using Rails with MySQL, and if you need more assistance I recommend Stack Overflow which has a very active Rails community.

The problem is that your `created_at` field doesn't have a default value - meaning that it is defined as `NOT NULL` but does not have a `DEFAULT`. If you are using MySQL 5.6.5 or higher, you can set the default to the current timestamp: https://optimize-this.blogspot.com/2012/04/datetime-default-now-finally-available.html

Rails 5 also has support for a programmatic default value: https://solidfoundationwebdev.com/blog/posts/default-model-attributes-in-rails

**Comment by solaiman** [comment]
Thanks for the help. That Issue is sorted now.
